### ISSUE TITLE
The example in the READMD.md do not panic when I pass in the wrong APIKEY and SECRET

### ISSUE THREAD

**Issue by bronze1man** [gigenet-projects/gcloud-golang-api#1]
The example in the READMD.md do not panic when I pass in the wrong APIKEY and SECRET.
It just return zero server.
Please return the correct error message in the err of the DescribeInstances api.

**Comment by gigenetdeveloper** [comment]
Tested the example snippet 
`panic: server error [SignatureDoesNotMatch] The signature you provided does not match.`
Please keep in mind that the examples provided in the package are just for testing, DO NOT RELY on this if you are in production environment. You should implement your own validation in your system.
