### ISSUE TITLE
Please document an example about how to create an instance in Region iad1.

### ISSUE THREAD

**Issue by bronze1man** [gigenet-projects/gcloud-golang-api#4]
The document at https://api.gigenetcloud.com/?go#runinstances only have an example , but that example do not have Region parameter. So I do not know how to create an instance in Region iad1.

**Comment by gigenetdeveloper** [comment]
Please check the full api documentation in our website. There is an example on how to get the list of available regions and deploy a new instance

https://api.gigenetcloud.com/#describeavailabilityzones
https://api.gigenetcloud.com/#describeregions
https://api.gigenetcloud.com/#runinstances
