### ISSUE TITLE
RunInstances should use url.QueryEscape to escape all input parameters (ImageId,InstanceType,...) 

### ISSUE THREAD

**Issue by bronze1man** [gigenet-projects/gcloud-golang-api#5]
https://github.com/gigenet-projects/gcloud-golang-api/blob/d7add5389ed1b35f54df9a384ddc5e13e6907303/api/RunInstances.go#L27

RunInstances should use url.QueryEscape to escape all input parameters (ImageId,InstanceType) ,so that the server can get correct input parameters with some special chars.

**Comment by gigenetdeveloper** [comment]
@bronze1man Some parameters only accept a set of value Including the ImageId. And other parameters are intentionally does not accept special characters, it could be an alphanumeric or a number

**Comment by bronze1man** [comment]
@gigenetdeveloper 
Since the golang type of imageId is string.  the Caller can pass in something like "1&Placement_AvailabilityZone=iad1" to change the AvailabilityZone of the created vps.
Sorry, but only accept alphanumeric or a number in this string in the server do not solve this correcting problem.
