### ISSUE TITLE
incompatible change make my code break.

### ISSUE THREAD

**Issue by bronze1man** [gigenet-projects/gcloud-golang-api#6]
https://github.com/gigenet-projects/gcloud-golang-api/commit/a1de45543d24d5398ac86e9b6d09f6488042d66a#diff-990bcb6ac5bd9e5ea64055fc98dc6a5b

```
 type runInstancesResponse struct {
-	Owner     string      `xml:"reservation>ownerId"`
-	Instances []*Instance `xml:"reservation>instances>item"`
+	Owner     string      `xml:"ownerId"`
+	Instances []*Instance `xml:"instancesSet>item"`
 }
```
This is a incompatible change to the old code.
This change stop me create new vps and create a lot of rubbish vps in my account.

**Comment by gigenetdeveloper** [comment]
Hi @bronze1man . You should still get the same set of return value from the API response. You will see in the change log that the return value is the same as before "(instances []*Instance, err error)"

For example to extract the value, you can still do:
```
for _, re := range res {
    fmt.Println(re.PublicIpAddress)
 }

```
Runinstances returns the already extracted data, so you don't actually access runInstancesResponse directly.

```
b, err = Request(api.server, api.ApiKey, api.secret, time.Now(), "RunInstances", buf.String())
body := &runInstancesResponse{}
err = xml.Unmarshal(b, &body)
if err != nil {
	return
}

instances = body.Instances
```

If you are an existing client of GigeNET please open a ticket so you can get more assistance.

**Comment by gigenetdeveloper** [comment]
@bronze1man also try to download again the package to make sure that you have the latest commits

**Comment by bronze1man** [comment]
The binary interface of the response had changed, so my old code will not work. It works when I update the code. But this incompatible change already created a lot of rubbish vps. And this incompatible change already force me to update my code. 
I think the incompatible change should be avoid in the future. 
You can create a new domain or api name to work with your new api interface, please do not change the old one.
For example, I will happy to see you create the api name like "RunInstancesV2" with "instancesSet".
And leave the old api name "RunInstances" with "reservation".
But since this incompatible change has already happened. Please do not change the binary interface  of "RunInstances" any more.

**Comment by bronze1man** [comment]
The problem is that I do not know I need to update my code when you change your server side binary interface of the response of "RunInstances".

Here is what I want:
* Please do not change the binary interface of api names without a security bug any more. For example please do not change the binary interface of api name "RunInstances" to fix this bug, it will create a lot of rubbish vps again.
* If you want to change the binary interface of some exist api name without a security bug in the future, please create a new api name with different name and leave the old one unchanged.
* If you want to change the binary interface of some exist api name because of a security bug in the future, please change the code that it can work with the new and the old version of your api name and make phone calls to all your users that can use the api system, so that they can update their code before you change.

what is the binary interface change?
* This change will make the unchanged old code not work correctly.
* For example:
    * change the xml name from "reservation" to "instancesSet" in the "RunInstances" response is a binary interface change, because the unchanged old code can not get the id and ip address from the created vps.
    * change add a new field "request" in the xml is not a binary interface change, because the unchanged old code can still work correct.
   * add a new api name is not binary interface change.
   * delete a api name is a binary interface change, because the unchanged old code will not work any more.
